/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package seguridades;

import archivo.CelArcBloNot;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author prof_tes_a
 */
public class CelPanPri extends javax.swing.JFrame {

    /**
     * Creates new form CelPanPri
     */
    public CelPanPri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskGen = new javax.swing.JDesktopPane();
        panBarEst = new javax.swing.JPanel();
        lblUsr = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArc = new javax.swing.JMenu();
        mnuArcNue = new javax.swing.JMenuItem();
        mnuArcAbr = new javax.swing.JMenuItem();
        mnuArcGua = new javax.swing.JMenuItem();
        mnuArcGuaCom = new javax.swing.JMenuItem();
        mnuArcCer = new javax.swing.JMenuItem();
        mnuArcSep1 = new javax.swing.JPopupMenu.Separator();
        mnuArcLogIngSis = new javax.swing.JMenuItem();
        mnuArcSep2 = new javax.swing.JPopupMenu.Separator();
        mnuArcSal = new javax.swing.JMenuItem();
        mnuVer = new javax.swing.JMenu();
        mnuVerBarEst = new javax.swing.JCheckBoxMenuItem();
        mnuMae = new javax.swing.JMenu();
        mnuMaeCel = new javax.swing.JMenuItem();
        mnuMaeLisCe = new javax.swing.JMenuItem();
        mnuAyu = new javax.swing.JMenu();
        mnuAyuAceDe = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CelularesTES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout dskGenLayout = new javax.swing.GroupLayout(dskGen);
        dskGen.setLayout(dskGenLayout);
        dskGenLayout.setHorizontalGroup(
            dskGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        dskGenLayout.setVerticalGroup(
            dskGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        getContentPane().add(dskGen, java.awt.BorderLayout.CENTER);

        panBarEst.setLayout(new java.awt.BorderLayout());

        lblUsr.setText("Usuario:");
        panBarEst.add(lblUsr, java.awt.BorderLayout.CENTER);

        getContentPane().add(panBarEst, java.awt.BorderLayout.SOUTH);

        mnuArc.setText("Archivo");

        mnuArcNue.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuArcNue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.jpg"))); // NOI18N
        mnuArcNue.setText("Nuevo...");
        mnuArcNue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArcNueActionPerformed(evt);
            }
        });
        mnuArc.add(mnuArcNue);

        mnuArcAbr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrir.gif"))); // NOI18N
        mnuArcAbr.setText("Abrir...");
        mnuArcAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArcAbrActionPerformed(evt);
            }
        });
        mnuArc.add(mnuArcAbr);

        mnuArcGua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuArcGua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        mnuArcGua.setText("Guardar...");
        mnuArcGua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArcGuaActionPerformed(evt);
            }
        });
        mnuArc.add(mnuArcGua);

        mnuArcGuaCom.setText("Guardar como...");
        mnuArcGuaCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArcGuaComActionPerformed(evt);
            }
        });
        mnuArc.add(mnuArcGuaCom);

        mnuArcCer.setText("Cerrar");
        mnuArcCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArcCerActionPerformed(evt);
            }
        });
        mnuArc.add(mnuArcCer);
        mnuArc.add(mnuArcSep1);

        mnuArcLogIngSis.setText("Log de ingreso al Sistema...");
        mnuArc.add(mnuArcLogIngSis);
        mnuArc.add(mnuArcSep2);

        mnuArcSal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuArcSal.setText("Salir");
        mnuArcSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArcSalActionPerformed(evt);
            }
        });
        mnuArc.add(mnuArcSal);

        jMenuBar1.add(mnuArc);

        mnuVer.setText("Ver");

        mnuVerBarEst.setSelected(true);
        mnuVerBarEst.setText("Barra de estado");
        mnuVerBarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerBarEstActionPerformed(evt);
            }
        });
        mnuVer.add(mnuVerBarEst);

        jMenuBar1.add(mnuVer);

        mnuMae.setText("Maestros");

        mnuMaeCel.setText("Celulares...");
        mnuMaeCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMaeCelActionPerformed(evt);
            }
        });
        mnuMae.add(mnuMaeCel);

        mnuMaeLisCe.setText("Listado de celulares...");
        mnuMaeLisCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMaeLisCeActionPerformed(evt);
            }
        });
        mnuMae.add(mnuMaeLisCe);

        jMenuBar1.add(mnuMae);

        mnuAyu.setText("Ayuda");

        mnuAyuAceDe.setText("Acerca de...");
        mnuAyuAceDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyuAceDeActionPerformed(evt);
            }
        });
        mnuAyu.add(mnuAyuAceDe);

        jMenuBar1.add(mnuAyu);

        jMenu1.setText("herramienta");

        jMenuItem1.setText("calculadora");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("mapaa");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 640, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArcSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArcSalActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_mnuArcSalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "CelularesTES", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mnuVerBarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerBarEstActionPerformed
        /*
        //Forma 1:
        if (mnuVerBarEst.isSelected())
        {
            panBarEst.setVisible(true);
        }
        else
        {
            panBarEst.setVisible(false);
        }
        */
        //Forma 2:
        panBarEst.setVisible(mnuVerBarEst.isSelected());
    }//GEN-LAST:event_mnuVerBarEstActionPerformed

    private void mnuArcNueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArcNueActionPerformed
        archivo.CelArcBloNot objArcBloNot=new archivo.CelArcBloNot();
        dskGen.add(objArcBloNot, JLayeredPane.DEFAULT_LAYER);
        objArcBloNot.setVisible(true);
    }//GEN-LAST:event_mnuArcNueActionPerformed

    private void mnuArcAbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArcAbrActionPerformed
        abrirCelArcBloNot();
    }//GEN-LAST:event_mnuArcAbrActionPerformed

    private void mnuArcGuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArcGuaActionPerformed
        guardarCelArcBloNot();
    }//GEN-LAST:event_mnuArcGuaActionPerformed

    private void mnuArcGuaComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArcGuaComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArcGuaComActionPerformed

    private void mnuArcCerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArcCerActionPerformed
        dskGen.getSelectedFrame().dispose();
    }//GEN-LAST:event_mnuArcCerActionPerformed

    private void mnuAyuAceDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyuAceDeActionPerformed
        ayuda.CelAyuAceDe objAyuAceDe=new ayuda.CelAyuAceDe(this, false);
        objAyuAceDe.setVisible(true);
        System.out.println("Fin del menú...");
    }//GEN-LAST:event_mnuAyuAceDeActionPerformed

    private void mnuMaeCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMaeCelActionPerformed
        maestros.CelMaeCel objMaeCel=new maestros.CelMaeCel();
        dskGen.add(objMaeCel, JLayeredPane.DEFAULT_LAYER);
        objMaeCel.setVisible(true);
    }//GEN-LAST:event_mnuMaeCelActionPerformed

    private void mnuMaeLisCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMaeLisCeActionPerformed
        maestros.CelMaeLisCel objMaeLisCel=new maestros.CelMaeLisCel();
        dskGen.add(objMaeLisCel, JLayeredPane.DEFAULT_LAYER);
        objMaeLisCel.setVisible(true);
    }//GEN-LAST:event_mnuMaeLisCeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CelPanPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CelPanPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CelPanPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CelPanPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CelPanPri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskGen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblUsr;
    private javax.swing.JMenu mnuArc;
    private javax.swing.JMenuItem mnuArcAbr;
    private javax.swing.JMenuItem mnuArcCer;
    private javax.swing.JMenuItem mnuArcGua;
    private javax.swing.JMenuItem mnuArcGuaCom;
    private javax.swing.JMenuItem mnuArcLogIngSis;
    private javax.swing.JMenuItem mnuArcNue;
    private javax.swing.JMenuItem mnuArcSal;
    private javax.swing.JPopupMenu.Separator mnuArcSep1;
    private javax.swing.JPopupMenu.Separator mnuArcSep2;
    private javax.swing.JMenu mnuAyu;
    private javax.swing.JMenuItem mnuAyuAceDe;
    private javax.swing.JMenu mnuMae;
    private javax.swing.JMenuItem mnuMaeCel;
    private javax.swing.JMenuItem mnuMaeLisCe;
    private javax.swing.JMenu mnuVer;
    private javax.swing.JCheckBoxMenuItem mnuVerBarEst;
    private javax.swing.JPanel panBarEst;
    // End of variables declaration//GEN-END:variables

    public void setUsuarioBarraEstado(String usuario)
    {
        lblUsr.setText("Usuario: " + usuario);
    }
    
    private boolean guardarArcTex(String strNomArc, String strTex)
    {
        boolean blnRes=true;
        try
        {
            java.io.FileWriter objFilWri=new java.io.FileWriter(strNomArc);
            java.io.BufferedWriter objBufWri=new java.io.BufferedWriter(objFilWri);
            java.io.PrintWriter objPriWri=new java.io.PrintWriter(objBufWri);
            objPriWri.print(strTex);
            objPriWri.close();
        }
        catch(java.io.IOException e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }
    
    private boolean abrirArcTex(String strNomArc, JTextArea txaTex)
    {
        boolean blnRes=true;
        try
        {
            String strCon=""; //Contenido del archivo.
            java.io.FileReader objFilRea=new java.io.FileReader(strNomArc);
            java.io.BufferedReader objBufRea=new java.io.BufferedReader(objFilRea);
            String strLin;
            while((strLin=objBufRea.readLine())!=null)
                strCon+=strLin + "\n";
            objBufRea.close();
            txaTex.setText(strCon);
        }
        catch(java.io.FileNotFoundException e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        catch(java.io.IOException e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }
    
    private boolean guardarCelArcBloNot()
    {
        boolean blnRes=true;
        try
        {
            String strArc;
            if (((CelArcBloNot)dskGen.getSelectedFrame()).getTitle().equals("Bloc de notas"))
            {
                JFileChooser objFilCho=new JFileChooser();
                objFilCho.setDialogTitle("Guardar");
                objFilCho.setFileSelectionMode(JFileChooser.FILES_ONLY);
                objFilCho.setCurrentDirectory(new File("C:\\"));
                //Filtrado (Opción 1):
                FileNameExtensionFilter objFilNamExt=new FileNameExtensionFilter("Archivos de texto", "txt");
                objFilCho.setFileFilter(objFilNamExt);
                //Filtrado (Opción 2):
//                objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
//                objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos java", "java"));
//                objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos php", "php", "php4", "phtml"));
                if (objFilCho.showSaveDialog(this)==JFileChooser.APPROVE_OPTION)
                {
                    strArc=objFilCho.getSelectedFile().getPath();
                    //Si no tiene la extensión "txt" agregarsela.
                    if (!strArc.toLowerCase().endsWith(".txt"))
                        strArc+=".txt";
                    if (guardarArcTex(strArc, ((CelArcBloNot)dskGen.getSelectedFrame()).txaPag.getText()))
                        ((CelArcBloNot)dskGen.getSelectedFrame()).setTitle(strArc);
        //            System.out.println("Directorio seleccionado: " + strArc);
        //            System.out.println("Texto: " + ((MenArcBloNot)dskGen.getSelectedFrame()).txaPag.getText());
                }
                else
                {
                    System.out.println("El usuario canceló");
                }
            }
            else
                guardarArcTex(((CelArcBloNot)dskGen.getSelectedFrame()).getTitle(), ((CelArcBloNot)dskGen.getSelectedFrame()).txaPag.getText());
        }
        catch(Exception e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }
    
    private boolean abrirCelArcBloNot()
    {
        boolean blnRes=true;
        try
        {
            String strArc;
            JFileChooser objFilCho=new JFileChooser();
            objFilCho.setDialogTitle("Abrir");
            objFilCho.setFileSelectionMode(JFileChooser.FILES_ONLY);
            objFilCho.setCurrentDirectory(new File("C:\\"));
            //Filtrado (Opción 1):
            FileNameExtensionFilter objFilNamExt=new FileNameExtensionFilter("Archivos de texto", "txt");
            objFilCho.setFileFilter(objFilNamExt);
            //Filtrado (Opción 2):
    //        objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
    //        objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos java", "java"));
    //        objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos php", "php", "php4", "phtml"));
            if (objFilCho.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
            {
                strArc=objFilCho.getSelectedFile().getPath();
                //Si no tiene la extensión "txt" agregarsela.
    //            if (!strArc.toLowerCase().endsWith(".txt"))
    //                strArc+=".txt";

                CelArcBloNot objArcBloNot=new CelArcBloNot();
                dskGen.add(objArcBloNot, JLayeredPane.DEFAULT_LAYER);
                objArcBloNot.setVisible(true);

                //abrirArcTex(strArc, ((MenArcBloNot)dskGen.getSelectedFrame()).txaPag);
                abrirArcTex(strArc, objArcBloNot.txaPag);
                ((CelArcBloNot)dskGen.getSelectedFrame()).setTitle(strArc);
    //            System.out.println("Directorio seleccionado: " + strArc);
    //            System.out.println("Texto: " + ((ifrProPal)dskGen.getSelectedFrame()).txaPag.getText());
            }
            else
            {
                System.out.println("El usuario canceló");
            }
        }
        catch(Exception e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }
    
}
